
// *** Code author: Smeagolheart (used/edited with permision by szef) ***

INCLUDE ~%MOD_FOLDER%/lib/S9MP-PSTLib.tph~

// *** Code author: Argent77 ***

// bs2
PRINT @07 

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btbs2/g-btbs2.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~ ~MOS0003.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btbs2/%file%~
      RET
        success
		DEST_FILE
    END
   // ACTION_IF (success) BEGIN //
	ACTION_IF (NOT success) BEGIN
	//// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	// //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// cla

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btcla/g-btcla.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btcla/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
	ACTION_IF (NOT success) BEGIN
	 //PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// def

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btdef/g-btdef.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2//g-btdef/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// med

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btmed/g-btmed.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~  BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btmed/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// lin

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btlin/g-btlin.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~ ~MOS0003.pvrz~ ~MOS0004.pvrz~ ~MOS0005.pvrz~ ~MOS0006.pvrz~ ~MOS0007.pvrz~ ~MOS0008.pvrz~  BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btlin/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// law

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btlaw/g-btlaw.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~ ~MOS0003.pvrz~ ~MOS0004.pvrz~ ~MOS0005.pvrz~ ~MOS0006.pvrz~ ~MOS0007.pvrz~ ~MOS0008.pvrz~   BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btlaw/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END


// sdb

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btsdb/g-btsdb.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~ ~MOS0003.pvrz~ ~MOS0004.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btsdb/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END


// shd

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btshd/g-btshd.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~ ~MOS0003.pvrz~ ~MOS0004.pvrz~ ~MOS0005.pvrz~ ~MOS0006.pvrz~ ~MOS0007.pvrz~ ~MOS0008.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btshd/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END


// pos

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btpos/g-btpos.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btpos/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END
/*
// ton

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btton.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0068.pvrz~ ~MOS0069.pvrz~ ~MOS0070.pvrz~ ~MOS0071.pvrz~ ~MOS0072.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END
*/
// jnw

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btjnw/g-btjnw.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btjnw/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END


// jol

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btjol/g-btjol.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btjol/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END


// por

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btpor/g-btpor.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btpor/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// sd1

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btsd1/g-btsd1.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btsd1/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// sh1

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btsh1/g-btsh1.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btsh1/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END
/*
// ttn

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btttn.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0073.pvrz~ ~MOS0074.pvrz~ ~MOS0075.pvrz~  BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END
*/
// que

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btque/g-btque.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ ~MOS0002.pvrz~  BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btque/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

// frm

// Installing MOS
ACTION_IF GAME_IS ~pstee~ BEGIN
COPY ~%MOD_FOLDER%/res/mos_v2/g-btfrm/g-btfrm.mos~ ~override~
  LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
  END

ACTION_IF (new_base_index >= 0) BEGIN
  // Installing PVRZ resources
  ACTION_FOR_EACH file IN ~MOS0000.pvrz~ ~MOS0001.pvrz~ BEGIN
    LAF INSTALL_PVRZ
      INT_VAR
        original_base_index
        new_base_index
      STR_VAR
        source_file = EVAL ~%MOD_FOLDER%/res/mos_v2/g-btfrm/%file%~
      RET
        success
		DEST_FILE
    END
    //ACTION_IF (success) BEGIN 
  ACTION_IF (NOT success) BEGIN
	// PRINT ~Successfully installed file %file% as %DEST_FILE%.~
	 //END ELSE BEGIN // else begin
      WARN ~Could not install file %file%!~
    END
  END
END
END

PRINT @06
PRINT @09
PRINT @11
